# Generated by Django 5.1.4 on 2024-12-28 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_triages'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.permissions')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.roles')),
            ],
        ),
    ]
